Pipfile, Pipfile.lock, build.sh, config/settings.py, congregate/management/commands/add_superuser.py
Deploying to render so that I can start giving front end devs some CRUD endpoints.
=> deploy-to-render

config/settings.py
Added previously removed Google environment variable back in. Updated environment variables in Render web service.
=> added google env variable back in

config/urls.py, congregate/serializers.py, congregate/urls.py, congregate/views.py
I created an endpoint that will display the list of a user's groups. Although the view is a ListCreateAPIView, the create group method is not working at this time.
=> list of user's groups endpoint

congregate/urls.py, congregate/views.py
Group home page endpoint is now working
=> group home endpoint

congregate/serializers.py, congregate/urls.py, congregate/views.py
I added an endpoint that will create a new event.
=> add event endpoint is working

congregate/serializers.py, congregate/urls.py, congregate/views.py
I created an endpoint that will add a user to a group. The user home page now shows a list of user's groups.
=> add user to group endpoint created, user home page shows list of user's groups

congregate/models.py, congregate/serializers.py, congregate/urls.py, congregate/views.py
The event home page endpoint and new activity endpoints have been created. Tested locally via Insomnia.
=> Event homepage and new activity endpoints active

README.md
=> README created and current API endpoints documented

README.md, congregate/serializers.py, congregate/urls.py, congregate/views.py
New group endpoint has been added
=> new group endpoint

congregate/serializers.py
Activity location has been added to activity serializer
=> added location to activity serializer

config/celery.py
Attempting to fix Heroku redis error
=> set ssl cert to none

config/celery.py
Updated event page endpoint response data at the request of front end devs
=> ssl cert to none again

congregate/views.py
Updated the create user to include given username, first name, last name, and avatar as URL. Tested locally via Insomnia.
=> updated create user to populate more fields

congregate/serializers.py, congregate/views.py
New user creation works with no username provided or with existing username. Tested locally via Insomnia.
=> New user creation works for existing username

config/celery.py, congregate/views.py
Added user.save() that was missing when adding first_name, last_name, and avatarURL to newly created users. Also added ssl certs for rediss:// Hekoru site.
=> Heroku redis needs certs

congregate/serializers.py
Added the list of vote objects to the activity serializer. Tested locally via Insomnia.
=> add vote list to activity serializer

README.md, config/settings.py, congregate/urls.py, congregate/views.py
Remove user from group endpoint now exists. Tested locally via Insomnia. Documentation updated.
=> remove user from group

congregate/urls.py, congregate/views.py
Fixed the bug where adding a new user responded status 403
=> fix join group permission bug

README.md
Updated documentation for users adding and leaving groups
=> join-leave-group-documentation

config/celery.py, congregate/views.py
The permission for PATCH on the ActivityUpdateDestroy view was fixed. Tested locally via Insomnia.
=> Activity update permission

config/celery.py, congregate/views.py
Fixed a bug where new users to a group were unable to vote on open, undecided events. Tested locally via Insomnia.
=> New user to group vote bug

config/celery.py
Removed comment code that didn't allow Heroku to deploy
=> Heroku deployment bug fixed

congregate/serializers.py
Added group id to event serializer
=> added group id to the event serializer

congregate/serializers.py
Upload list removed from serializers
=> remote upload list form serializers

config/celery.py, congregate/serializers.py
Fixed the bug where EventSerializer was not recognizing group_id during new event creation. Tested locally via Insomnia.
=> Group id issue on new event creation fixed

config/celery.py
Fixed Celery settings that caused a 500 error in production
=> Fixed Celery production bug

congregate/serializers.py
Group avatar added to serializer
=> group avatar added to serializer

config/celery.py
Celery production code change for SSL cert
=> celery production code change

config/urls.py, congregate/urls.py, congregate/views.py
Cleaned up unnecessary views and urls
=> got rid of unnecessary views and urls

congregate/serializers.py
If the event is decided, the event serializer will display activities in order of votes. Tested locally via Insomnia.
=> if event decided, activities listed in order of votes

config/settings.py
Removed unnecessary settings and variables from settings.py
=> removed unnecessary settings

congregate/serializers.py, congregate/views.py
Updated the create event view to set event.decided to true if event.voting is false. Tested locally via Insomnia.
=> Event crated with voting false sets event to decided

congregate/serializers.py
Group avatar returned with event in EventSerializer. Tested locally via Insomnia.
=> Added group avatar to event serializer
